name: Linting and testing checks

on:
  pull_request:
    types: ["opened", "reopened", "synchronize"]
    paths:
      - "inspect_weave/**"
      - "tests/**"

env:
  UV_PROJECT_ENVIRONMENT: true
    
jobs:
  checks:
    runs-on: ubuntu-latest
    name: Run Linting and testing checks
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run Linting and testing checks
        run: |
          uv run ruff check .
          uv run ruff format --diff .
          uv run mypy .
          uv run pytest . 
